In [59]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
data=pd.read_csv(r"C:\Users\sairam\Desktop\practice_data.csv")
data.head()

,F2,F9,F12,F25,F26,F28,F34,F41,F44,F47,F50,F54,F60,F65,F66,F70,F76,Class
0,0.760188,0.760204,0.619986,0.760240,0.620108,0.619993,0.760608,0.760374,0.620730,1.000000,0.760261,1.000000,1.000000,1.000000,0.760608,1.000000,1.000000,0
1,0.760200,0.760197,1.000000,0.760207,1.000000,1.000000,0.760266,0.760261,1.000000,0.760312,0.760219,0.760200,0.760191,0.760288,0.760266,0.760276,0.760189,0
2,1.000000,1.000000,1.000000,1.000000,0.760267,1.000000,1.000000,1.000000,1.000000,0.760275,1.000000,0.620175,1.000000,0.760289,1.000000,0.620498,1.000000,0
3,0.760202,0.760199,0.760188,0.760203,0.760209,0.760202,0.760391,0.760339,0.760424,0.760253,0.760221,0.760202,0.760202,0.760259,0.760391,0.760248,0.760424,0
4,0.760193,1.000000,0.760199,1.000000,0.760213,0.762225,0.760250,1.000000,0.765161,0.760188,0.760219,1.000000,0.762225,1.000000,0.760250,1.000000,0.765161,0

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   F2      216 non-null    float64
 1   F9      216 non-null    float64
 2   F12     216 non-null    float64
 3   F25     216 non-null    float64
 4   F26     216 non-null    float64
 5   F28     216 non-null    float64
 6   F34     216 non-null    float64
 7   F41     216 non-null    float64
 8   F44     216 non-null    float64
 9   F47     216 non-null    float64
 10  F50     216 non-null    float64
 11  F54     216 non-null    float64
 12  F60     216 non-null    float64
 13  F65     216 non-null    float64
 14  F66     216 non-null    float64
 15  F70     216 non-null    float64
 16  F76     216 non-null    float64
 17  Class   216 non-null    int64
dtypes: float64(17), int64(1)
memory usage: 30.5 KB

In [61]:
data.describe()

,F2,F9,F12,F25,F26,F28,F34,F41,F44,F47,F50,F54,F60,F65,F66,F70,F76,Class
count,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.00000
mean,0.944017,0.879594,0.912507,0.882076,0.916634,0.914385,0.945053,0.878528,0.910754,0.914187,0.922438,0.917557,0.910260,0.926293,0.927470,0.924446,0.913629,0.99537
std,0.088212,0.134606,0.118926,0.135913,0.111482,0.120349,0.087938,0.133135,0.118509,0.117768,0.111748,0.112099,0.116391,0.108614,0.113704,0.112601,0.117873,1.15133
min,0.760188,0.619900,0.619900,0.620007,0.619923,0.619912,0.760247,0.619912,0.619959,0.619913,0.619978,0.619985,0.619921,0.619936,0.619965,0.619995,0.620101,0.00000
25%,0.954593,0.760200,0.761168,0.760216,0.776447,0.760421,0.959350,0.760261,0.760384,0.760574,0.881263,0.808884,0.760243,0.864084,0.891516,0.873389,0.760392,0.00000
50%,0.983509,0.965825,0.977208,0.974264,0.974640,0.982810,0.984699,0.958259,0.973832,0.978551,0.983646,0.981559,0.979558,0.986217,0.989069,0.987293,0.984737,0.50000
75%,1.000000,0.990696,0.998058,0.992577,0.999344,0.996907,1.000000,0.981642,0.995380,0.995696,1.000000,0.997665,0.996937,1.000000,1.000000,0.999471,0.995462,2.00000
max,1.000000,1.000000,1.000000,1.002096,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.00000

In [62]:
corr=data.corr()
corr

,F2,F9,F12,F25,F26,F28,F34,F41,F44,F47,F50,F54,F60,F65,F66,F70,F76,Class
F2,1.000000,0.288828,0.133393,0.283360,0.259141,0.141820,0.982344,0.275284,0.128086,0.194636,0.618443,-0.013258,0.203849,0.148029,0.616861,0.000720,0.211224,0.269306
F9,0.288828,1.000000,0.480796,0.993717,0.400273,0.490477,0.284680,0.991406,0.475179,0.358939,0.355965,0.186581,0.320154,0.412324,0.377413,0.225671,0.337127,-0.174619
F12,0.133393,0.480796,1.000000,0.485101,0.384052,0.997115,0.137174,0.477150,0.991662,0.084600,0.213627,-0.117830,0.286842,0.422666,0.231906,-0.086995,0.297348,-0.188479
F25,0.283360,0.993717,0.485101,1.000000,0.405487,0.494534,0.288882,0.991103,0.477141,0.365933,0.362431,0.200181,0.328083,0.415810,0.384766,0.233962,0.345926,-0.154215
F26,0.259141,0.400273,0.384052,0.405487,1.000000,0.389657,0.262833,0.396217,0.379212,0.197066,0.226732,0.286247,0.329775,0.214505,0.240682,0.298549,0.339862,0.151746
F28,0.141820,0.490477,0.997115,0.494534,0.389657,1.000000,0.142752,0.486735,0.993097,0.090456,0.220128,-0.113162,0.295878,0.428941,0.239477,-0.079896,0.307719,-0.171809
F34,0.982344,0.284680,0.137174,0.288882,0.262833,0.142752,1.000000,0.287513,0.132548,0.199104,0.618850,-0.010423,0.214459,0.148973,0.622368,0.007287,0.217952,0.281888
F41,0.275284,0.991406,0.477150,0.991103,0.396217,0.486735,0.287513,1.000000,0.474277,0.357460,0.348268,0.177796,0.320654,0.406964,0.373905,0.222554,0.336981,-0.183684
F44,0.128086,0.475179,0.991662,0.477141,0.379212,0.993097,0.132548,0.474277,1.000000,0.076601,0.204969,-0.131654,0.283671,0.417137,0.224148,-0.095317,0.293352,-0.189931
F47,0.194636,0.358939,0.084600,0.365933,0.197066,0.090456,0.199104,0.357460,0.076601,1.000000,0.422509,0.399504,0.339519,0.272268,0.436501,0.426268,0.350381,0.183130
F50,0.618443,0.355965,0.213627,0.362431,0.226732,0.220128,0.618850,0.348268,0.204969,0.422509,1.000000,0.124927,0.322097,0.265929,0.994571,0.140217,0.334019,0.162924
F54,-0.013258,0.186581,-0.117830,0.200181,0.286247,-0.113162,-0.010423,0.177796,-0.131654,0.399504,0.124927,1.000000,0.326750,0.211963,0.135464,0.976926,0.342030,0.185642
F60,0.203849,0.320154,0.286842,0.328083,0.329775,0.295878,0.214459,0.320654,0.283671,0.339519,0.322097,0.326750,1.000000,0.261396,0.343374,0.369574,0.995039,0.192986
F65,0.148029,0.412324,0.422666,0.415810,0.214505,0.428941,0.148973,0.406964,0.417137,0.272268,0.265929,0.211963,0.261396,1.000000,0.280945,0.235279,0.275340,-0.160041
F66,0.616861,0.377413,0.231906,0.384766,0.240682,0.239477,0.622368,0.373905,0.224148,0.436501,0.994571,0.135464,0.343374,0.280945,1.000000,0.161550,0.354222,0.160449
F70,0.000720,0.225671,-0.086995,0.233962,0.298549,-0.079896,0.007287,0.222554,-0.095317,0.426268,0.140217,0.976926,0.369574,0.235279,0.161550,1.000000,0.381608,0.152552
F76,0.211224,0.337127,0.297348,0.345926,0.339862,0.307719,0.217952,0.336981,0.293352,0.350381,0.334019,0.342030,0.995039,0.275340,0.354222,0.381608,1.000000,0.198849
Class,0.269306,-0.174619,-0.188479,-0.154215,0.151746,-0.171809,0.281888,-0.183684,-0.189931,0.183130,0.162924,0.185642,0.192986,-0.160041,0.160449,0.152552,0.198849,1.000000

In [63]:
cor_target = abs(corr["Class"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.17]
relevant_features

F2       0.269306
F9       0.174619
F12      0.188479
F28      0.171809
F34      0.281888
F41      0.183684
F44      0.189931
F47      0.183130
F54      0.185642
F60      0.192986
F76      0.198849
Class    1.000000
Name: Class, dtype: float64

In [66]:
X = data.iloc[:,:-1]
y = data.iloc[: ,-1]

In [103]:
y

0      0
1      0
2      0
3      0
4      0
      ..
211    2
212    3
213    1
214    2
215    3
Name: Class, Length: 216, dtype: int64

In [122]:
from sklearn.model_selection import train_test_split

X_train,X_test ,y_train, y_test = train_test_split(X,y,
                                                   test_size=0.30,
                                                   random_state=0,
                                                  shuffle = True,
                                                  stratify = y)

print('training data shape is :{}.'.format(X_train.shape))
print('training label shape is :{}.'.format(y_train.shape))
print('testing data shape is :{}.'.format(X_test.shape))
print('testing label shape is :{}.'.format(y_test.shape))

training data shape is :(151, 17).
training label shape is :(151,).
testing data shape is :(65, 17).
testing label shape is :(65,).

In [123]:
from sklearn.svm import SVC
# Building a Support Vector Machine on train data
svc_model = SVC(kernel='poly',gamma=8)
svc_model.fit(X_train, y_train)

SVC(gamma=8, kernel='poly')

In [127]:
X_test[0:1]

,F2,F9,F12,F25,F26,F28,F34,F41,F44,F47,F50,F54,F60,F65,F66,F70,F76
124,0.978391,0.993603,0.982583,0.995041,0.99175,0.99021,0.986009,0.993136,0.994611,0.973228,0.961566,0.996627,1.0,0.996469,0.985451,0.990588,1.0

In [140]:
y_test[0:1]

124    0
Name: Class, dtype: int64

In [124]:
from sklearn.metrics import accuracy_score, confusion_matrix
predictions= svc_model .predict(X_test)
print('ground truth')
print(list(y_test))
print('predictions by ML model')
print(predictions)
percentage=svc_model.score(X_test,y_test)
res=confusion_matrix(y_test,predictions)
print("confusion matrix")
print(res)
# check the accuracy on the training set
print(svc_model.score(X_train, y_train))
print(svc_model.score(X_test, y_test))
print(f"Test set:{len(X_test)}")
print(f"Accuracy={percentage*100}%")

ground truth
[0, 0, 3, 0, 0, 3, 0, 0, 1, 1, 0, 0, 1, 3, 1, 2, 1, 0, 0, 3, 1, 0, 0, 0, 3, 2, 3, 0, 1, 0, 0, 2, 0, 2, 0, 2, 3, 2, 0, 0, 0, 3, 0, 3, 0, 1, 1, 3, 0, 2, 0, 3, 2, 1, 0, 0, 0, 2, 2, 1, 0, 0, 0, 2, 0]
predictions by ML model
[0 0 3 0 0 3 0 0 1 1 0 0 1 3 1 2 1 0 0 3 1 0 0 0 3 2 3 0 1 0 0 2 0 2 0 2 3
 2 0 0 0 3 0 3 0 1 1 3 0 2 0 3 2 1 0 0 0 2 2 1 0 0 0 2 0]
confusion matrix
[[32  0  0  0]
 [ 0 11  0  0]
 [ 0  0 11  0]
 [ 0  0  0 11]]
0.9933774834437086
1.0
Test set:65
Accuracy=100.0%

In [ ]:
i=[0 0 3 0 0 3 0 0 1 1 0 0 1 3 1 2 1]

In [139]:
 print('enter the value for f2')
f2=float(input())
print('enter the value for f9')
f9=float(input())
print('enter the value for f12')
f12=float(input())
print('enter the value for f25')
f25=float(input())
print('enter the value for f26')
f26=float(input())
print('enter the value for f28')
f28=float(input())
print('enter the value for f34')
f34=float(input())
print('enter the value for f41')
f41=float(input())
print('enter the value for f44')
f44=float(input())
print('enter the value for f47')
f47=float(input())
print('enter the value for f50')
f50=float(input())
print('enter the value for f54')
f54=float(input())
print('enter the value for f60')
f60=float(input())
print('enter the value for f65')
f65=float(input())
print('enter the value for f66')
f66=float(input())
print('enter the value for f70')
f70=float(input())
print('enter the value for f76')
f76=float(input())
inp=[[f2,f9,f12,f25,f26,f28,f34,f41,f44,f47,f50,f54,f60,f65,f66,f70,f76]]
print(inp)
out=svc_model.predict(inp)
if out==0:
    print('C')
elif out==1:
    print('T1')
elif out==2:
    print('T2')
else:
    print('T3')

1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
enter the value for
1
[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]
[0]